on:
  push:
    branches: [ master,release_branch* ]
  pull_request:
    branches: [ master,release_branch* ]
  workflow_dispatch:

permissions: read-all

jobs:
  build-windows:
    if: github.repository_owner == 'oneapi-src'
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Windows build environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Build Loader on Latest Windows
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -D CMAKE_BUILD_TYPE=Release -D BUILD_INSTALLER=1 ..
          cmake --build . --target package
