on:
  push:
    branches: [ master,release_branch* ]
  pull_request:
    branches: [ master,release_branch* ]
  workflow_dispatch:

permissions: read-all

jobs:
  build-windows:
    if: github.repository_owner == 'oneapi-src'
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Windows build environment
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: x64
      - name: Build Loader on Latest Windows
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -D CMAKE_BUILD_TYPE=Release -D BUILD_INSTALLER=1 ..
          cmake --build . --target package
