on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions: read-all

jobs:
  build-linux:
    if: github.repository_owner == 'oneapi-src'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: hendrikmuhs/ccache-action@v1
      - name: Build Loader on Latest Ubuntu
        run: |
          mkdir build
          cd build
          cmake \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache \
            -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -D CMAKE_BUILD_TYPE=Release \
            ..
          make -j$(nproc)
      - env:
          ZEL_LIBRARY_PATH: ${{ github.workspace }}/build/lib
          ZE_ENABLE_NULL_DRIVER: '1'
          ZE_ENABLE_LOADER_DEBUG_TRACE: '1'
        run: ./build/bin/tests

  build-windows:
    if: github.repository_owner == 'oneapi-src'
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build Loader on Latest Windows
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
      - env:
          ZEL_LIBRARY_PATH: ${{ github.workspace }}/build/bin/Release
          ZE_ENABLE_NULL_DRIVER: '1'
          ZE_ENABLE_LOADER_DEBUG_TRACE: '1'
        run: ./build/bin/Release/tests.exe
